# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

title: Bitembassy TLV
author: Bitembassy TLV
timezone: Asia/Jerusalem
url: "https://www.bitembassy.org"
baseurl: /
root: /
theme: landscape
twitter: BitcoinemBassy
github_path: "https://github.com/bitembassy/bitembassy.org/blob/master/source/"
share_img: '/img/og-image.png'

new_post_name: :category/:year-:month-:day-:title.md
permalink: :category/:year-:month-:day-:title.html
category_dir: ''

per_page: 0

deploy:
  type: git
  repo: git@github.com:bitembassy/bitembassy.org.git
  branch: gh-pages

markdown:
  render:
    html: true
    linkify: true
    typographer: true
  anchors:
    level: 2

stylus:
  compress: true
  include css: true
