# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

title: Bitembassy TLV
author: Bitembassy TLV
timezone: IST
url: https://bitembassy.github.io/bitembassy.org/
root: /bitembassy.org/
theme: landscape

deploy:
  type: git
  repo: git@github.com:bitembassy/bitembassy.org.git
  branch: gh-pages

markdown:
  render:
    html: true
    linkify: true
    typographer: true
  anchors:
    level: 2

stylus:
  compress: true
  include css: true
